### ISSUE TITLE
Hat jemand OpenJDK 21 getestet?

### ISSUE THREAD

**Issue by leoheitmannruiz** [tudagrade/haudy#52]
Ich habe bisher OpenJDK 17 verwendet, ohne Probleme. Die aktuelle Homebrew Anweisungen installieren OpenJDK 21. Wenn ich mit OpenJDK 21 den Gradle Task mainBuildSubmission ausführe bekomme ich die folgende Fehlermeldungen. Sollte sich vielleicht auf OpenJDK 17 beschränkt werden?

```
Unsupported Java. 
Your build is currently configured to use Java 21 and Gradle 8.4.

Possible solution:
 - Use Java 20 as Gradle JVM: Open Gradle settings 
 - Open Gradle wrapper settings, change `distributionUrl` property to use compatible Gradle version and reload the project
```

**Comment by LukasKlenner** [comment]
Hast du deine Daten in der build.gradle.kts Datei deine Daten eingetragen (https://wiki.tudalgo.org/exercises/export-upload/)? Konnte das Problem zwar reproduzieren, aber nur, wenn ich die build.gradle.kts nicht ausgefüllt habe. Nach dem Ausfüllen hat es trotzdem funktioniert.

**Comment by leoheitmannruiz** [comment]
Mit ausgefüllter build.gradle.kts tritt der Fehler be mir nicht auf. Hätte ich testen sollen. Danke!
